redis:
  image: redis
  container_name: redis
db:
  image: postgres:9.5
  container_name: db
  environment:
    POSTGRES_PASSWORD: none
vote:
  image: rakeshdyx/voting-app
  container_name: vote
  ports:
    - "5000:80"
  links:
    - redis
worker:
  image: rakeshdyx/worker
  container_name: worker
  links:
    - redis
    - db
result:
  image: rakeshdyx/result
  container_name: result
  ports:
    - "5001:80"
  links:
    - db


  